---
heat_template_version: 2015-04-30

description: Xura HOT template to deploy OMU unit

parameters:
  omu_flavor_name:
    type: string
    description: Flavor Name to be used
  omu_image:
    type: string
    description: Image Name to be used
  omu_image_id:
    type: string
    description: Image ID to be used - in case of block device mapping
  tenant_network_name:
    type: string
    description: Tenant Network Name with DHCP
  tenant_network_id:
    type: string
    description: Tenant Network ID with DHCP
  tenant_security_group_name:
    type: string
    description: Tenant Security Group Name
  admin_network_port:
    type: string
    description: Port ID on Admin Network
  sz_network_port:
    type: string
    description: Port ID on Admin Network

resources:
  tenant_network_port:
    type: OS::Neutron::Port
    properties:
      # network_id: { get_param: tenant_network_id }
      network: { get_param: tenant_network_name }
      security_groups:
        - { get_param: tenant_security_group_name }

  omu_unit:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: omu_flavor_name }
      networks:
        - port: { get_resource: tenant_network_port }
        - port: { get_param: admin_network_port }
        - port: { get_param: sz_network_port }
      # image: omu_image
      block_device_mapping_v2:
        -
          boot_index: 0
          delete_on_termination: true
          device_name: vda
          image_id: { get_param: omu_image_id }
          volume_size: 10
#      user_data_format: RAW
#      user_data:
#        str_replace:
#          template: |
#            #!/bin/sh
#            # Simple success signal
#            wc_notify --data-binary '{"status": "SUCCESS"}'
#
#          params:
#            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
