---
heat_template_version: 2015-04-30

description: Xura HOT template to deploy OMU unit

parameters:
  dev_mode:
    type: boolean
    description: Dev Mode for the Cloud-Init Script which performs development stuff
    default: false
#  keypair_name:
#    type: string
#    description: Keypair for the unit
  unit_name:
    type: string
    description: Hostname of the Unit
  domain_name:
    type: string
    description: Domain Name of the Unit
  omu_flavor_name:
    type: string
    description: Flavor Name to be used
  omu_image:
    type: string
    description: Image Name to be used
  omu_image_id:
    type: string
    description: Image ID to be used - in case of block device mapping
#  tenant_network_name:
#    type: string
#    description: Tenant Network Name with DHCP
#  tenant_network_id:
#    type: string
#    description: Tenant Network ID with DHCP
#  tenant_security_group_name:
#    type: string
#    description: Tenant Security Group Name
  admin_network_port:
    type: string
    description: Port ID on Admin Network
  sz_network_port:
    type: string
    description: Port ID on Admin Network
  admin_mac_address:
    type: string
    description: Admin Port Mac Address
  admin_ip_address:
    type: string
    description: Admin Network IP Address
  admin_netmask:
    type: string
    description: Admin Network Netmask
  admin_gw:
    type: string
    description: Admin Network default GW
  sz_mac_address:
    type: string
    description: Secure Zone Port Mac Address
  sz_ip_address:
    type: string
    description: Secure Zone Network IP Address
  sz_netmask:
    type: string
    description: Secure Zone Network Netmask

resources:
#  tenant_network_port:
#    type: OS::Neutron::Port
#    properties:
#      # network_id: { get_param: tenant_network_id }
#      network: { get_param: tenant_network_name }
#      security_groups:
#        - { get_param: tenant_security_group_name }

  omu_unit:
    type: OS::Nova::Server
    properties:
      name: { get_param: unit_name }
      flavor: { get_param: omu_flavor_name }
      networks:
        #- port: { get_resource: tenant_network_port }
        - port: { get_param: admin_network_port }
        - port: { get_param: sz_network_port }
      # image: omu_image
      # key_name: { get_param: keypair_name }
      config_drive: true
      user_data_format: RAW
      user_data:
        str_replace:
          template: { get_file: ./script/omu_software_config.sh }
          params:
            _DEVMODE_: { get_param: dev_mode }
            _ADMIN_MAC_: { get_param: admin_mac_address }
            _ADMIN_IP_: { get_param: admin_ip_address }
            _ADMIN_NETMASK_: { get_param: admin_netmask }
            _ADMIN_GW_: { get_param: admin_gw }
            _SZ_MAC_: { get_param: sz_mac_address }
            _SZ_IP_: { get_param: sz_ip_address }
            _SZ_NETMASK_: { get_param: sz_netmask }
            _HOSTNAME_: { get_param: unit_name }
            _DOMAINNAME_: { get_param: domain_name }

      block_device_mapping_v2:
        -
          boot_index: 0
          delete_on_termination: true
          device_name: vda
          image_id: { get_param: omu_image_id }
          volume_size: 20
